#35 イベントの日程登録機能実装
moriyadetteiu/clapton pull request #101
Opened 2020-12-12 12:01 UTC by beryl0123

resolve: #35

## この PR で実装される内容
イベントの日程登録機能

## 悩ましい（見てほしい）部分

## 確認

-   [ ] test 画面からイベントの日付を入力し登録される
![localhost_3000_events_create](https://user-images.githubusercontent.com/72699098/101983227-f660f680-3cbc-11eb-80ee-a23c6313b0a5.png)
![localhost_3000_events_create (1)](https://user-images.githubusercontent.com/72699098/101983229-f95be700-3cbc-11eb-926c-db1b67fe26b2.png)
![localhost_3000_events_create (2)](https://user-images.githubusercontent.com/72699098/101983232-fbbe4100-3cbc-11eb-8278-a2b76611a99f.png)
![image](https://user-images.githubusercontent.com/72699098/101983236-07aa0300-3cbd-11eb-85dd-8bddfca828c2.png)
![image](https://user-images.githubusercontent.com/72699098/101983240-0e387a80-3cbd-11eb-97a8-542f0a9f0298.png)

## 備考

2020-12-13 21:58 UTC, moriyadetteiu requested changes
@beryl0123 
コメントをご確認いただければと思います。
違和感、疑問な部分などは適宜突っ込んでくださいー。

また、このブランチに依存しているブランチがある場合は別でissueを立ててでもよいですが、フロントエンドのテストコードも書いていただけると助かります。

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +  syncedDate!: string
単に文字列を渡しているだけなので、 `v-model` を使って受け渡すようにしてほしいです。
確かpropsとemitの組み合わせでできたはずなので

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +  syncedDate!: string
`{ type: String as PropType<string> }` -> `{ type: string }` だと駄目でしょうか？
確かオブジェクトを引数に渡すときに必要だった記憶が（間違ってたら言ってください）

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +  private rules!: String
このコンポーネント内で使われてないので、削除してほしいです。

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +          outlined
ここら辺はpropsで指定していない引数はすべて `v-text-field` に渡す形がいいと思います。
https://qiita.com/shinobu_shiva/items/e0c458aa6c1e683a9881#5-transparent-wrappers

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +  private label?: String
上のコメントと合わせて、不要になると思います。

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +  private menu: Boolean = false
Boolean値なので、 `isOpenMenu` のような名前でどうでしょう？
https://qiita.com/GinGinDako/items/6e8b696c4734b8e92d2b

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/common/AppDatePicker.vue
> +      >
今後未選択の場合でも使う場合が想定されるので、バリデーションは別コンポーネントへ切り出しませんか？
`validate-date-picker` のようなコンポーネントでラップしたものを別で用意するイメージです。

多分下でコメントしている `v-model` を使うようにするのと合わせるとできると思います。

2020-12-13 21:58 UTC, moriyadetteiu commented on front/components/events/EventForm.vue
> +        <template v-for="(eventDate, index) in syncedEventDates">
文脈的に多分 `v-row` を v-for するのがよさそうな気がしますが、微妙な感じでしょうか？

2020-12-13 21:58 UTC, moriyadetteiu commented on front/pages/events/create.vue
> +  eventDates: EventDateInput[] = []
日付を入れないことはないと思うので、デフォルトで1つ日付の入力欄が表示されているほうがいいと思います
具体的には `created` イベントフックを用意して、 `this.addDate()` をする感じです。

2020-12-13 21:58 UTC, moriyadetteiu commented on front/pages/events/create.vue
> +  eventDates: EventDateInput[] = []
こちらのメソッド、プロパティもアクセス修飾子をつけていただけると助かります。

2020-12-13 21:58 UTC, moriyadetteiu commented on laravel/app/GraphQL/Mutations/CreateEvent.php
> +        $eventDates = $event->eventDates()->createMany($eventData['event_dates']);
いい感じの書き方だと思います！

2020-12-16 14:59 UTC, beryl0123 commented on front/components/events/EventForm.vue
> +        <template v-for="(eventDate, index) in syncedEventDates">
全体的なコード的に<v-col cols=12> をv-rowで囲ってるいるものかと思ってました。
コメントのとおりだだとv-row内にv-rowがある（または、<template v-for="(eventDate, index) in syncedEventDates">の前にv-rowを一旦閉じる？）事になると思われるますが、この認識であってますか？

2020-12-18 09:39 UTC, moriyadetteiu commented on front/components/events/EventForm.vue
> +        <template v-for="(eventDate, index) in syncedEventDates">
@beryl0123 
はい、一回 `v-row` を閉じる認識です。
UserFormで確認した感じでは、 `v-col` の12が2つと、 `v-row` 2つの中に `v-col` 入れるパターンで見た目上の差異はなさそうだったので、問題ないと思います。

コンポーネントの文脈的に行ごとに使うものなので、 `UserForm` も `v-row` を行ごとに区切ったほうがよかったかもですね・・・。

2021-02-13 17:48 UTC, moriyadetteiu approved these changes
ご対応ありがとうございました！

2021-02-13 17:48 UTC, merged